let countries = {
    "Algeria": "rest_of_africa",
    "Angola": "rest_of_africa",
    "Benin": "west_africa",
    "Botswana": "rest_of_africa",
    "Burkina Faso": "west_africa",
    "Burundi": "rest_of_africa",
    "Cameroon": "rest_of_africa",
    "Cape Verde": "west_africa",
    "Central rest_of_african Republic": "rest_of_africa",
    "Chad": "rest_of_africa",
    "Comoros": "rest_of_africa",
    "Congo (DR Congo)": "rest_of_africa",
    "Djibouti": "rest_of_africa",
    "Egypt": "rest_of_africa",
    "Equatorial Guinea": "rest_of_africa",
    "Eritrea": "rest_of_africa",
    "Eswatini": "rest_of_africa",
    "Ethiopia": "rest_of_africa",
    "Gabon": "rest_of_africa",
    "Gambia": "west_africa",
    "Ghana": "west_africa",
    "Guinea": "west_africa",
    "Guinea-Bissau": "west_africa",
    "Ivory Coast": "rest_of_africa",
    "Kenya": "rest_of_africa",
    "Lesotho": "rest_of_africa",
    "Liberia": "west_africa",
    "Libya": "rest_of_africa",
    "Madagascar": "rest_of_africa",
    "Malawi": "rest_of_africa",
    "Mali": "west_africa",
    "Mauritania": "west_africa",
    "Mauritius": "rest_of_africa",
    "Morocco": "rest_of_africa",
    "Mozambique": "rest_of_africa",
    "Namibia": "rest_of_africa",
    "Niger": "west_africa",
    "Nigeria": "west_africa",
    "Rwanda": "rest_of_africa",
    "São Tomé and Príncipe": "rest_of_africa",
    "Senegal": "west_africa",
    "Seychelles": "rest_of_africa",
    "Sierra Leone": "west_africa",
    "Somalia": "rest_of_africa",
    "South rest_of_africa": "rest_of_africa",
    "South Sudan": "rest_of_africa",
    "Sudan": "rest_of_africa",
    "Tanzania": "rest_of_africa",
    "Togo": "west_africa",
    "Tunisia": "rest_of_africa",
    "Uganda": "rest_of_africa",
    "Zambia": "rest_of_africa",
    "Zimbabwe": "rest_of_africa",
    "Afghanistan": "asia",
    "Armenia": "asia",
    "Azerbaijan": "asia",
    "Bahrain": "asia",
    "Bangladesh": "asia",
    "Bhutan": "asia",
    "Brunei": "asia",
    "Cambodia": "asia",
    "China": "asia",
    "Hong Kong": "Unknown Territories",
    "India": "asia",
    "Indonesia": "asia",
    "Iran": "asia",
    "Iraq": "asia",
    "Israel": "asia",
    "Japan": "asia",
    "Jordan": "asia",
    "Kazakhstan": "asia",
    "Kuwait": "asia",
    "Kyrgyzstan": "asia",
    "Laos": "asia",
    "Lebanon": "asia",
    "Malaysia": "asia",
    "Maldives": "asia",
    "Mongolia": "asia",
    "Myanmar": "asia",
    "Nepal": "asia",
    "North Korea": "asia",
    "Oman": "asia",
    "Pakistan": "asia",
    "Palestine": "asia",
    "Philippines": "asia",
    "Qatar": "asia",
    "Saudi Arabia": "asia",
    "Singapore": "asia",
    "South Korea": "asia",
    "Sri Lanka": "asia",
    "Syria": "asia",
    "Taiwan": "asia",
    "Tajikistan": "asia",
    "Thailand": "asia",
    "Timor-Leste": "asia",
    "Turkey": "asia",
    "Turkmenistan": "asia",
    "United Arab Emirates": "asia",
    "Uzbekistan": "asia",
    "Vietnam": "asia",
    "Yemen": "asia",
    "Åland Islands": "europe",
    "Albania": "europe",
    "Andorra": "europe",
    "Austria": "europe",
    "Belarus": "europe",
    "Belgium": "europe",
    "Bosnia and Herzegovina": "europe",
    "Bulgaria": "europe",
    "Croatia": "europe",
    "Cyprus": "europe",
    "Czechia": "europe",
    "Denmark": "europe",
    "Estonia": "europe",
    "Faroe Islands": "europe",
    "Finland": "europe",
    "France": "europe",
    "Germany": "europe",
    "Greece": "europe",
    "Hungary": "europe",
    "Iceland": "europe",
    "Ireland": "europe",
    "Italy": "europe",
    "Kosovo": "europe",
    "Latvia": "europe",
    "Liechtenstein": "europe",
    "Lithuania": "europe",
    "Luxembourg": "europe",
    "Malta": "europe",
    "Moldova": "europe",
    "Monaco": "europe",
    "Montenegro": "europe",
    "Netherlands": "europe",
    "North Macedonia": "europe",
    "Norway": "europe",
    "Poland": "europe",
    "Portugal": "europe",
    "Romania": "europe",
    "Russia": "europe",
    "San Marino": "europe",
    "Serbia": "europe",
    "Slovakia": "europe",
    "Slovenia": "europe",
    "Spain": "europe",
    "Sweden": "europe",
    "Switzerland": "europe",
    "Ukraine": "europe",
    "United Kingdom": "europe",
    "Vatican City": "europe",
    "Antigua and Barbuda": "north_america",
    "Bahamas": "north_america",
    "Barbados": "north_america",
    "Belize": "north_america",
    "Canada": "north_america",
    "Costa Rica": "north_america",
    "Cuba": "north_america",
    "Dominica": "north_america",
    "Dominican Republic": "north_america",
    "El Salvador": "north_america",
    "Grenada": "north_america",
    "Guatemala": "north_america",
    "Haiti": "north_america",
    "Honduras": "north_america",
    "Jamaica": "north_america",
    "Mexico": "north_america",
    "Nicaragua": "north_america",
    "Panama": "north_america",
    "Saint Kitts and Nevis": "north_america",
    "Saint Lucia": "north_america",
    "Saint Vincent and the Grenadines": "north_america",
    "Trinidad and Tobago": "north_america",
    "United States": "north_america",
    "Australia": "Oceania",
    "Fiji": "Oceania",
    "Kiribati": "Oceania",
    "Marshall Islands": "Oceania",
    "Micronesia": "Oceania",
    "Nauru": "Oceania",
    "New Zealand": "Oceania",
    "Palau": "Oceania",
    "Papua New Guinea": "Oceania",
    "Samoa": "Oceania",
    "Solomon Islands": "Oceania",
    "Tonga": "Oceania",
    "Tuvalu": "Oceania",
    "Vanuatu": "Oceania",
    "Argentina": "south_america",
    "Bolivia": "south_america",
    "Brazil": "south_america",
    "Chile": "south_america",
    "Colombia": "south_america",
    "Ecuador": "south_america",
    "Guyana": "south_america",
    "Paraguay": "south_america",
    "Peru": "south_america",
    "Suriname": "south_america",
    "Uruguay": "south_america",
    "Venezuela": "south_america",
    "American Samoa": "Unknown Territories",
    "Antarctica": "Unknown Territories",
    "Bermuda": "Unknown Territories",
    "Bouvet Island": "Unknown Territories",
    "British Indian Ocean Territory": "Unknown Territories",
    "British Virgin Islands": "Unknown Territories",
    "Christmas Island": "Unknown Territories",
    "Cocos (Keeling) Islands": "Unknown Territories",
    "Falkland Islands": "Unknown Territories",
    "French Guiana": "Unknown Territories",
    "French Polynesia": "Unknown Territories",
    "French Southern and Antarctic Lands": "Unknown Territories",
    "Guam": "Unknown Territories",
    "Macau": "Unknown Territories",
    "Montserrat": "Unknown Territories",
    "New Caledonia": "Unknown Territories",
    "Niue": "Unknown Territories",
    "Norfolk Island": "Unknown Territories",
    "Northern Mariana Islands": "Unknown Territories",
    "Pitcairn Islands": "Unknown Territories",
    "Puerto Rico": "Unknown Territories",
    "Saint Barthélemy": "Unknown Territories",
    "Saint Helena, Ascension and Tristan da Cunha": "Unknown Territories",
    "Saint Martin": "Unknown Territories",
    "Saint Pierre and Miquelon": "Unknown Territories",
    "Sint Maarten": "Unknown Territories",
    "South Georgia": "Unknown Territories",
    "Turks and Caicos Islands": "Unknown Territories",
    "United States Minor Outlying Islands": "Unknown Territories",
    "United States Virgin Islands": "Unknown Territories",
    "Wallis and Futuna": "Unknown Territories",
    "Western Sahara": "Unknown Territories",
    "Côte d'Ivoire": "west_africa"
}

export default countries